table:
    chatrange: 30
    allowRake: true
    minRaiseIsAlwaysBB: true
    defaults:
        elimination: false
        minBuy: 10000
        maxBuy: 100000
        sb: 500
        bb: 1000
        ante: 100
        dynamicAnteFreq: 0
        rake: 0.05