table:
    chatRange: 30
    allowRake: false
    defaults:
        elimination: false
        minRaiseIsAlwaysBB: true
        minBuy: 0
        maxBuy: 100000
        sb: 500
        bb: 1000
        ante: 0
        dynamicFrequency: 0
        rake: 0.05
        minRaise: 200
log:
    enableLog: true
    dateFormat: 'dd/MM/yyyy HH:mm:ss'