options:
  general:
    autoUpdate: true
    cleanupOnDisable: true
  log:
    enableLog: false
    dateFormat: 'dd/MM/yyyy HH:mm:ss'
  chat:
    displayTag: true
    colorTag: '&1'
    colorNormalMessage: '&f'
    colorErrorMessage: '&c'
    colorHighlight: '&6'
    chatRange: 30
  generalDefaults:
    allowRebuys: true
    displayTurnsPublicly: false
  poker:
    fixRake: -1
    rakeToStack: false
    defaults:
      elimination: false
      minRaiseIsAlwaysBB: true
      minBuy: 0
      maxBuy: 100000
      sb: 500
      bb: 1000
      ante: 0
      dynamicFrequency: 0
      rake: 0.05
      minRaise: 200
  blackjack:
    serverNeverDealer: true
    defaults:
      allowDoubleDown: true
      minBet: 100
      serverDealer: false
      amountOfDecks: 5