name: UltimateCards
description: 'The ultimate Texas Holdem and Blackjack plugin for Bukkit!'
version: 1.2.3
main: com.github.norbo11.UltimateCards
depend: [Vault]
softdepend: [TagAPI]
commands:
    table:
        description: 'Controls the tables of the UltimateCards plugin.'
    cards:
        description: 'Controls generic commands of the UltimateCards plugin.'
    poker:
        description: 'Controls all poker commands of the UltimateCards plugin.'
    blackjack:
        description: 'Controls all blackjack commands of the UltimateCards plugin.'
    bj:
        description: 'Controls all blackjack commands of the UltimateCards plugin.'
permissions:
    ucards:
        description: 'Gives access to every command of the UltimateCards plugin.'
        children:
            ucards.table: true
            ucards.cards: true
            ucards.poker: true
            ucards.blackjack: true
        default: op
    ucards.table:
        description: 'Gives access to /table commands.'
        default: false
    ucards.cards:
        description: 'Gives access to /cards commands.'
        default: false
    ucards.poker:
        description: 'Gives access to /poker commands.'
        default: false
    ucards.blackjack:
        description: 'Gives access to /blackjack commands.'
        default: false