name: UltimatePoker
description: 'The ultimate plugin for Texas Holdem on Bukkit!'
version: 1.1.1
main: com.github.norbo11.UltimatePoker
commands:
    table:
        description: 'Controls the tables of the UltimatePoker plugin.'
        usage: 'Usage: /<command>'
    tbl:
        description: 'Controls the tables of the UltimatePoker plugin. Alias for /table.'
        usage: 'Usage: /<command>'
    tables:
        description: 'Lists all created poker tables. Alias for /poker tables.'
        usage: 'Usage: /<command>'
    hand:
        description: 'Controls the hand commands of the UltimatePoker plugin.'
        usage: 'Usage: /<command>'
    poker:
        description: 'Controls all generic commands of the UltimatePoker plugin.'
        usage: 'Usage: /<command>'
    pkr:
        description: 'Controls all generic commands of the UltimatePoker plugin. Alias for /poker.'
        usage: 'Usage: /<command>'
permissions:
    upoker.*:
        description: 'Gives access to every command of the UltimatePoker plugin.'
        children:
            upoker.table: true
            upoker.play: true
            upoker.tp: true
        default: op
    upoker.table:
        description: 'Gives access to all /table commands. These tables are used for table managment and creation only.'
        default: false
    upoker.play:
        description: 'Gives access to all /hand commands and /poker sit/leave. Without this, your players cannot play.'
        default: false
    upoker.tp:
        description: 'Gives access to /poker tp and automatically TPs the player when they do /poker sit.'
        default: false