name: UltimatePoker
description: 'The ultimate plugin for Texas Holdem on Bukkit!'
version: 0.1
main: com.github.Norbo11.UltimatePoker
commands:
    table:
        description: 'Controls the tables of the UltimatePoker plugin.'
        usage: 'Usage: /<command>'
<<<<<<< HEAD
    tables:
        description: 'Lists all created tables. Alias for /table list.'
        usage: 'Usage: /<command>'
    hand:
        description: 'Controls the hand commands.'
        usage: 'Usage: /<command>'        
=======
    pk:
        description: 'Controls the tables of the UltimatePoker plugin. Alias for /table.'
        usage: 'Usage: /<command>'
    tables:
        description: 'Lists all created tables. Alias for /table list.'
        usage: 'Usage: /<command>'
>>>>>>> dc2025a689dd38f6adc063612beeb247891ae7ed
permissions:
    upoker.*:
        description: 'Gives access to every command of the UltimatePoker plugin.'
        children:
            upoker.create.table: true
        default: op
    upoker.table.create:
        description: 'Gives access to /table createtable'
        default: op