options:
  general:
    autoUpdate: true
    cleanupOnDisable: true
  log:
    enableLog: false
    dateFormat: 'dd/MM/yyyy HH:mm:ss'
  chat:
    displayTag: true
    colorTag: '&1'
    colorNormalMessage: '&f'
    colorErrorMessage: '&c'
    colorHighlight: '&6'
  generalDefaults:
    allowRebuys: true
    displayTurnsPublicly: false
    autoStart: 0
    minBuy: 0
    maxBuy: 100000
    publicChatRange: 30
  poker:
    fixRake: -1
    defaults:
      minRaiseIsAlwaysBB: true
      sb: 500
      bb: 1000
      ante: 0
      dynamicFrequency: 0
      rake: 0.05
      minRaise: 200
  blackjack:
    defaults:
      allowDoubleDown: true
      minBet: 100
      amountOfDecks: 5